### PR TITLE
Copying cwebp lib to a custom directory

### PR DESCRIPTION
**Pull request by sethu1012**
Code has been modified to allow the developer to specify a custom location where webp libraries can be copied

### CODE REVIEW

**Comment by CrackerKSR** [comment]
If you are active please reply. I want to have a quick discussion on this

**Comment by sethu1012** [comment]
@CrackerKSR what do you want to discuss about?

**Comment by CrackerKSR** [comment]
I want to use it in android but it shows cwebp_tmp is not found. The folder is not being created.
Should I use different path to work in android?

**Comment by sethu1012** [comment]
Ran this code on a web app I was working on previously. 

I'm not sure why you're getting that error. Can you please reproduce the error in a sample application and push it to GitHub? I'll fork it and let you know the cause/fix.

**Comment by CrackerKSR** [comment]
It is related to path I think. I just used context to get cache and asset path and it creates temp folder on cache path and copies the webp tool into the temp. But now when I try to execute the command it shows permission denied error. I will share the codes and errors asap.

**Comment by sethu1012** [comment]
Is the issue resolved?

**Comment by CrackerKSR** [comment]
> Is the issue resolved?

I was able to copy the libwebp tools and access them in execution method. And this time  the issue is Permission. it shows Permission Denied.  I am not sure from where theese tools should run I tried app specific locations like cache, temp, data etc.

**Pull request merged**
